###
GET http://localhost:3000/api/reviews/

###
GET http://localhost:3000/api/reviews/0b1e8d61-24ad-4ab2-a7cf-f0dd09ced1f1

###
GET http://localhost:3000/api/reviews/company/91bdef63-585e-4eaf-8050-8456c40b95d3

###
POST http://localhost:3000/api/reviews/e90a07d8-7620-428b-8837-fe9cc9bcf7e6
Content-Type: application/json

{
    "companyId": "",
    "userName": "dsadasdasd",
    "userPicture": "gmolin",
    "pros": "Nice Nice Nice Nice Nice",
    "cons": "Bad Bad Bad Bad Bad",
    "overall": "vey nice",
    "totalRating": 4,
    "ratingCriteriaInterview": 2,
    "ratingCriteriaOnboarding": 3,
    "ratingCriteriaSupervision": 2,
    "ratingCriteriaLearning": 2,
    "ratingCriteriaCodingPractices": 3,
    "ratingCriteriaPerks": 3,
    "ratingCriteriaCulture": 2,
    "salary": 1500,
    "duration": 6,
    "coverLetter": "none",
    "cv": "none"
}

###
PUT http://localhost:3000/api/reviews/b7415998-3f92-4752-8233-0d7efacb5b57
Content-Type: application/json

{
    "companyId": "8990a061-6729-47dc-a1c9-70e7aa49dd57",
    "userName": "gmolin",
    "userPicture": "gmolin",
    "pros": "Nice fucking job yeah yeah",
    "cons": "the moentoring could have been a bit better",
    "overall": "Very nice",
    "totalRating": 3,
    "ratingCriteriaInterview": 4,
    "ratingCriteriaOnboarding": 3,
    "ratingCriteriaSupervision": 2,
    "ratingCriteriaLearning": 3,
    "ratingCriteriaCodingPractices": 1,
    "ratingCriteriaPerks": 4,
    "ratingCriteriaCulture": 2,
    "salary": 3000,
    "duration": 8,
    "coverLetter": "none",
    "cv": "none",
    "upVotes": 22,
    "upVoteUsers": ["npminof"],
    "downVotes": 0,
    "downVoteUsers": true 
}

###
DELETE http://localhost:3000/api/reviews/f9a514be-556d-49d0-9592-c3847921a42e
Content-Type: application/json

{
    "user": "hopham"
}