###
GET http://localhost:3000/api/reviews/

###
POST http://localhost:3000/api/reviews/1f5e58b9-a0bf-45ab-aac7-3fbb2ca94d16
Content-Type: application/json

{
    "companyId": "",
    "userName": "gmolin",
    "userPicture": "gmolin",
    "pros": ["Nice"],
    "cons": ["Ok"],
    "overall": "Very nice",
    "totalRating": 3.4,
    "ratingCriteriaInterview": 1.3,
    "ratingCriteriaOnboarding": 33.2,
    "ratingCriteriaSupervision": 2.3,
    "ratingCriteriaLearning": 1,
    "ratingCriteriaCodingPractices": 3,
    "ratingCriteriaPerks": 5,
    "ratingCriteriaCulture": 5,
    "salary": 2750,
    "duration": 6,
    "coverLetter": "none",
    "cv": "none"
}

###
PUT http://localhost:3000/api/reviews/d606f37e-c637-48db-8544-2ad290533c79
Content-Type: application/json

{
    "companyName": "Wunderdog",
    "companyDescription": "Software Development Agency",
    "logoURL": "https://www.itewiki.fi/thumb.php?src=https://www.itewiki.fi/write/logos/wunderdog.png&size=x100",
    "companyURL": "https://wunderdog.fi/",
    "companyLocation": "Helsinki, Finland"
}

###
GET http://localhost:3000/health

###
GET http://localhost:3000/api/reviews/1

###
DELETE http://localhost:3000/api/reviews/c569ddff-430a-463e-be86-7082a04ed2d2
