###
GET http://localhost:3000/api/reviews/

###
GET http://localhost:3000/api/reviews/525cfccb-dd76-4101-b971-2a18bd0ace62

###
GET http://localhost:3000/api/reviews/company/e3f9f26a-cd04-419a-b367-84e704adb419

###
POST http://localhost:3000/api/reviews/6c4bb5ed-1fd0-4013-8d02-8c14b9694a05
Content-Type: application/json

{
    "companyId": "",
    "userName": "hoang",
    "userPicture": "gmolin",
    "pros": ["Nice"],
    "cons": ["Ok"],
    "overall": "Very nice",
    "totalRating": 5,
    "ratingCriteriaInterview": 4,
    "ratingCriteriaOnboarding": 3,
    "ratingCriteriaSupervision": 2,
    "ratingCriteriaLearning": 2,
    "ratingCriteriaCodingPractices": 3,
    "ratingCriteriaPerks": 4,
    "ratingCriteriaCulture": 2,
    "salary": 1500,
    "duration": 6,
    "coverLetter": "none",
    "cv": "none"
}

###
PUT http://localhost:3000/api/reviews/9f274917-8b14-4fab-954d-a936b67aa2ac
Content-Type: application/json

{
    "companyId": "6c4bb5ed-1fd0-4013-8d02-8c14b9694a05",
    "userName": "gmolin",
    "userPicture": "gmolin",
    "pros": ["Nice"],
    "cons": ["Ok"],
    "overall": "Very nice",
    "totalRating": 1,
    "ratingCriteriaInterview": 4,
    "ratingCriteriaOnboarding": 3,
    "ratingCriteriaSupervision": 2,
    "ratingCriteriaLearning": 2,
    "ratingCriteriaCodingPractices": 3,
    "ratingCriteriaPerks": 4,
    "ratingCriteriaCulture": 2,
    "salary": 3000,
    "duration": 8,
    "coverLetter": "none",
    "cv": "none"
}

###
DELETE http://localhost:3000/api/reviews/c569ddff-430a-463e-be86-7082a04ed2d2

