name: Deployment Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  modules:
    name: Installing modules
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        working-directory: ./server
        run: npm install
  integration_test:
    needs: [modules]
    name: Backend Integration Testing
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#client') }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Modules
        working-directory: ./server
        run: npm install
      - name: Run Jest
        working-directory: ./server
        run: npm run test:int
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
  deployment:
    needs: [integration_test]
    name: Heroku Deployment
    if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ' '), '#deploy') }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hivesights" #Must be unique in Heroku
          heroku_email: "gerhard@minimumbadass.com"
          healthcheck: "https://hivesights.herokuapp.com/health"
          checkstring: "ok"
          delay: 10
  bump_version:
    needs: [integration_test, deployment]
    name: Bump version and push tag
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main

